= Projektantrag
Julian Jaklitsch
1.0.0, 2021-10-21: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]



== Projektname:

   Cafeteria Karten

== Projektleiter:

    Julian Jaklitsch

== Projektmitglieder:

 Julian Jaklitsch

== Projektbeschreibung:

Ein Programm, das hilft den Umsatz in der Cafeteria zu steigern. Am Schulanfang wird an jeden eine Karte gegeben, mit dieser Karte kann man in der Cafeteria bezahlen. Zum Aufladen der Karte geht man zu einem Automaten in der jeweiligen Schule dort kann man in 5 Euro Schritten seine Karte aufladen. Wenn man die Karte verliert, ist das kein Problem da alles in einer Datenbank gespeichert wurde und so bald man sie als gestohlen/verloren meldet wird die Karte gesperrt. Wenn man dann eine neue Karte braucht, zahlt man 5 Euro, damit auf die Karte geachtet wird.

== Meilensteine:

1.	Meilenstein: Das zugreifen auf Datenbanken
2.	Meilenstein: Die Funktion, um Profile anzulegen
3.	Meilenstein: Karten Nummer erstellen und Profilen zuordnen
4.	Meilenstein: fein Schlief



